site_name: Rojo Documentation
repo_name: rojo-rbx/rojo
repo_url: https://github.com/rojo-rbx/rojo

theme:
  name: material
  palette:
    primary: 'Red'
    accent: 'Red'

nav:
  - Home: index.md
  - Why Rojo?: why-rojo.md
  - Guide:
    - Installation: guide/installation.md
    - Creating a Game with Rojo: guide/new-game.md
    - Porting an Existing Game to Rojo: guide/existing-game.md
    - Migrating from 0.4.x to 0.5.x: guide/migrating-to-epiphany.md
  - Reference:
    - Fully vs Partially Managed Rojo: reference/full-vs-partial.md
    - Project Format: reference/project-format.md
    - Sync Details: reference/sync-details.md
  - Rojo Alternatives: rojo-alternatives.md
  - Rojo Internals:
    - Internals Overview: internals/overview.md

extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true